Controllers/CategoriesTempController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BulkyBook1Web.Data;
using BulkyBook1Web.Models;

namespace BulkyBook1Web.Controllers
{
    public class CategoriesTempController : Controller
    {
        private readonly ApplicationDBContext _context;

        public CategoriesTempController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: CategoriesTemp
        public async Task<IActionResult> Index(int pg=1)
        {
            List<Category> categories = _context.Categories.ToList();

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;
            int recsCount = categories.Count;
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = categories.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            return View(data);
            // return _context.Categories != null ? 
            // View(await _context.Categories.ToListAsync()) :
            // Problem("Entity set 'ApplicationDBContext.Categories'  is null.");
        }

        // GET: CategoriesTemp/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: CategoriesTemp/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriesTemp/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DisplayOder,CreatedDataTime")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: CategoriesTemp/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: CategoriesTemp/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DisplayOder,CreatedDataTime")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: CategoriesTemp/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: CategoriesTemp/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDBContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        
        
    }
}

Controllers/UsersController.cs
using BulkyBook1Web.Data;
using BulkyBook1Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Services.Graph;

namespace BulkyBook1Web.Controllers;

public class UsersController : Controller
{
    private readonly ApplicationDBContext _db;

   
    public UsersController(ApplicationDBContext db)
    {
        _db = db;
    }
    // GET
    public IActionResult Index()
    {
        var usersFromDb = _db.Users.ToList();
        return View(usersFromDb);    }
    //GET
    public IActionResult Register()
    {
        return View();
    }
    
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Register(User obj)
    {
        if (ModelState.IsValid)
        {
            _db.Users.Add(obj); //not add data in database yet
            _db.SaveChanges(); // SaveChanges will save date we input in the form to database
            TempData["Success"] = "User created  successfully";// Make notification
            return RedirectToAction("Index");
            //User RedirectToAction when we turn back to Index view when we submit in Create category view
            // if we want to return other view, use ("Index","other controller")
        }
        return View(obj);
    }
    
    public IActionResult Login()
    {
        return View();
    }

    //GET
    public IActionResult Edit(int? id)
    {
        if (id == null||id==0)
        {
            return NotFound();
        }
        var UserFormDb = _db.Users.Find(id);
        // var CategoryFormDbFirst = _db.Categories.FirstOrDefault(u=>u.Id==id);
        // var CategoryFormDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
        if (UserFormDb==null)
        {
            return NotFound();
        }
        return View(UserFormDb);
    }
    
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(User obj)
    {
        // if (obj.Name==obj.DisplayOder.ToString())
        // {
        //     ModelState.AddModelError("CustomError","The DisplayOrder cannot exactly match the Name");
        // }
        if (ModelState.IsValid)
        {
            _db.Users.Update(obj);
            _db.SaveChanges(); 
            TempData["Success"] = "Category updated  successfully";

            return RedirectToAction("Index");
        }
        return View(obj);
    }
    
    public IActionResult Delete(int? id)
    {
        if (id == null||id==0)
        {
            return NotFound();
        }
        var userFormDb = _db.Users.Find(id);
       
        if (userFormDb==null)
        {
            return NotFound();
        }
        return View(userFormDb);
    }
    
    //POST
    [HttpPost,ActionName("Delete")]//Change action name(DeleteCategoryPOST -> Delete)
    [ValidateAntiForgeryToken]
    public IActionResult DeleteUserPost(int? id)
    {
        var obj = _db.Users.Find(id);
        if (obj==null)
        {
            return NotFound();
        }
        _db.Users.Remove(obj);
        _db.SaveChanges(); 
        TempData["Success"] = "Category deleted  successfully";
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string search)
    {
        ViewData["Getuserdata"] = search;
        var userQuery = from x in _db.Users select x;
        if (!string.IsNullOrEmpty(search))
        {
            userQuery = userQuery.Where(x=>x.name.Contains(search)||x.email.Contains(search));
        }

        return View(await userQuery.AsTracking().ToListAsync());
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBook1Web</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" /> *@
    @* <link rel="stylesheet" href="~/css/font-awesome.css"> *@
    @* <link rel="stylesheet" href="~/css/style.css"/> *@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href='https://css.gg/details-more.css' rel='stylesheet'>
    @* <link rel="stylesheet" href="~/BulkyBook1Web.styles.css" asp-append-version="true" /> *@
</head>
<html>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link "  asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link "  asp-controller="CategoriesTemp" asp-action="Index">Category Temp</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link "  asp-controller="Users" asp-action="Index">User</a>
                    </li>
                </ul>
                <ul class="login">
                    <li class="login-position"></li>
                    <a class="btn btn-secondary my-sm-0" asp-controller="Users" asp-action="Login"> Sign in </a>
                    <a class="btn btn-primary my-sm-0" asp-controller="Users" asp-action="Register"> Sign up </a>
                </ul>
            </div>
        </div>
    </nav>
        
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification" />
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted bg-dark">
    <div class="container">
        &copy; 2021 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
        toastr.options.progressBar = true;
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
        toastr.options.progressBar = true;
    </script>
}