Models/Category.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BulkyBook1Web.Models;

public class Category
{
    [Key]//Make id is a key
    public int  Id{ get; set; }
    [Required]//Make name is required
    public string Name { get; set; }
    [DisplayName("Display Order")]//Use DisplayName to display what we want to display in the view
    [Range(1,100,ErrorMessage ="Display Order must between 1 to 100 only !!!")]//Make min and max value
    public int DisplayOder { get; set; }
    [DisplayName("Create DataTime")]
    public DateTime CreatedDataTime { get; set; } = DateTime.Now;
}

Controllers/CategoriesController.cs
using BulkyBook1Web.Data;
using BulkyBook1Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook1Web.Controllers;

public class CategoriesController : Controller
{
    private readonly ApplicationDBContext _db;

    public CategoriesController(ApplicationDBContext db)
    {
        _db = db;
    }

    // GET all category from DB
    public IActionResult Index()
    {
        var categoryFromDb = _db.Categories.ToList();
        return View(categoryFromDb);
    }
    
    //GET
    public IActionResult CreateCategory()
    {
        return View();
    }
    
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult CreateCategory(Category obj)
    {
        if (obj.Name==obj.DisplayOder.ToString())
        {
            // Can use key"name" to get Errormessage under the field
            ModelState.AddModelError("CustomError","The DisplayOrder cannot exactly match the Name");
        }
        if (ModelState.IsValid)
        {
            _db.Categories.Add(obj); //not add data in database yet
            _db.SaveChanges(); // SaveChanges will save date we input in the form to database
            TempData["Success"] = "Category created  successfully";// Make notification
            return RedirectToAction("Index");
            //User RedirectToAction when we turn back to Index view when we submit in Create category view
            // if we want to return other view, use ("Index","other controller")
        }
        return View(obj);
    }
    //GET
    public IActionResult EditCategory(int? id)
    {
        if (id == null||id==0)
        {
            return NotFound();
        }
        var categoryFormDb = _db.Categories.Find(id);
        // var CategoryFormDbFirst = _db.Categories.FirstOrDefault(u=>u.Id==id);
        // var CategoryFormDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
        if (categoryFormDb==null)
        {
            return NotFound();
        }
        return View(categoryFormDb);
    }
    
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult EditCategory(Category obj)
    {
        if (obj.Name==obj.DisplayOder.ToString())
        {
            ModelState.AddModelError("CustomError","The DisplayOrder cannot exactly match the Name");
        }
        if (ModelState.IsValid)
        {
            _db.Categories.Update(obj);
            _db.SaveChanges(); 
            TempData["Success"] = "Category updated  successfully";

            return RedirectToAction("Index");
        }
        return View(obj);
    }
    
    public IActionResult DeleteCategory(int? id)
    {
        if (id == null||id==0)
        {
            return NotFound();
        }
        var categoryFormDb = _db.Categories.Find(id);
       
        if (categoryFormDb==null)
        {
            return NotFound();
        }
        return View(categoryFormDb);
    }
    
    //POST
    [HttpPost,ActionName("Delete")]//Change action name(DeleteCategoryPOST -> Delete)
    [ValidateAntiForgeryToken]
    public IActionResult DeleteCategoryPOST(int? id)
    {
        var obj = _db.Categories.Find(id);
        if (obj==null)
        {
            return NotFound();
        }
        _db.Categories.Remove(obj);
        _db.SaveChanges(); 
        TempData["Success"] = "Category deleted  successfully";
        return RedirectToAction("Index");
    }
}

Views/Categories/CreateCategory.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr/>
        </div>
        @* get all message validation on top *@
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            @* don't need "Name" when we have asp-for *@
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOder"></label>
            <input asp-for="DisplayOder" class="form-control" />
            <span asp-validation-for="DisplayOder" class="text-danger"></span>
        </div>
        @* <div class="mb-3"> *@
        @*     <label asp-for="CreatedDataTime"></label> *@
        @*     <input asp-for="CreatedDataTime" class="form-control" /> *@
        @* </div> *@
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Categories" asp-action="Index" class="btn btn-primary" style="width: 150px">Back to list</a>
    </div>
</form>

    @* Make all validation done in client side(Not reload everytime when click button) that make web faster  *@
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Views/Categories/DeleteCategory.cshtml
@model Category

@* to distinguish between functions *@
<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr/>
        </div>
        @* get all message validation on top *@
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            @* don't need "Name" when we have asp-for *@
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOder"></label>
            <input asp-for="DisplayOder" disabled class="form-control"/>
        </div>
        @* <div class="mb-3"> *@
        @*     <label asp-for="CreatedDataTime"></label> *@
        @*     <input asp-for="CreatedDataTime" class="form-control" /> *@
        @* </div> *@
        <button type="submit" class="btn btn-danger" style="width: 150px">Delete</button>
        <a asp-controller="Categories" asp-action="Index" class="btn btn-primary" style="width: 150px">Back to list</a>
    </div>
</form>

    @* Make all validation done in client side(Not reload everytime when click button) that make web faster  *@
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Views/Categories/EditCategory.cshtml
@model Category

@* to distinguish between functions *@
<form method="post" asp-action="EditCategory">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr/>
        </div>
        @* get all message validation on top *@
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            @* don't need "Name" when we have asp-for *@
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOder"></label>
            <input asp-for="DisplayOder" class="form-control" />
            <span asp-validation-for="DisplayOder" class="text-danger"></span>
        </div>
        @* <div class="mb-3"> *@
        @*     <label asp-for="CreatedDataTime"></label> *@
        @*     <input asp-for="CreatedDataTime" class="form-control" /> *@
        @* </div> *@
        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="Categories" asp-action="Index" class="btn btn-primary" style="width: 150px">Back to list</a>
    </div>
</form>

    @* Make all validation done in client side(Not reload everytime when click button) that make web faster  *@
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Views/Categories/Index.cshtml
@model List<Category>

@{
    ViewData["Title"] = "Category";
}

<!DOCTYPE html>

<html>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Category</h1>
        </div>
    <div class="col-6 text-end">
        <a class="btn btn-primary" asp-controller="Categories" asp-action="CreateCategory">
            <i class="bi bi-journal-plus"></i> Create
        </a>
    </div>
</div>
    <br />
    <body>
    <div>
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            Category ID
                        </th>
                        <th>
                            Category Name
                        </th>
                        <th>
                            Display Order
                        </th>
                        <th>
                            CreatedDataTime
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var obj in Model)
                    {
                        <tr>
                            @* <td width="20%"> *@
                            @*     @obj.Id *@
                            @* </td> *@
                            <td width="20%">
                                @obj.Name
                            </td>
                            <td width="20%">
                                @obj.DisplayOder
                            </td>
                            <td width="20%">
                                @* @obj.CreatedDataTime *@
                            </td>
                            <td width="20%">
                                @* @obj.CreatedDataTime *@
                            </td>
                            <td>
                                <div class="w-75 btn-group" role="group">
                                    <a asp-controller="Categories" asp-action="EditCategory" asp-route-id="@obj.Id" class="btn btn-sm btn-outline-info">
                                        <i class="bi bi-pencil-fill"></i>
                                    </a>
                                    <a asp-controller="Categories" asp-action="DeleteCategory" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                        <i class="bi bi-trash3-fill"></i>
                                    </a>
                                </div>
                                
                                
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </body>
</div>
</html>